repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ ., --fix, --diff ]
      # Run the formatter.
      - id: ruff-format
        args: [ . ]
