site_name: cli-surf Docs
site_url: https://ryansurf.github.io/cli-surf
site_description: Documentation for cli-surf
site_author: ryansurf

repo_url: https://github.com/ryansurf/cli-surf
repo_name: cli-surf

theme:
  name: material

nav:
    - index.md
    - General:
      - FAQ: faq.md
    - Developers:
      - Installation: install.md
      - Setup: setup.md
    - Contributing:
      - Styling: styling.md
      - Tests: tests.md
      - Structure: structure.md
