name: Greetings

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  greeting:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'all-contributors[bot]' && github.actor != 'ryansurf' }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Hi! Thanks for opening your first issue! 🎉 We're excited to see your contribution. If you find this project interesting or helpful, we'd be thrilled if you could give it a star ⭐ Your support means a lot to us! 😊"
          pr-message: "👋 Hi! Thanks for submitting your first pull request! 🎉 We really appreciate your effort to improve this project. If you're enjoying your experience here and find the project interesting, we'd be over the moon if you could give it a star ⭐ It helps us grow and motivates us to keep improving! 🚀"
